services:
  web:
    build: .
    ports:
      - "8092:8092"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432/cafe_db
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - BUCKET_NAME=cafe-data
    networks:
      - coolify
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cafe_db
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - coolify

volumes:
  pg-data:

networks:
  coolify:
    external: true